
spring:
  application:
    name: dubbo-product
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
cloud:
  nacos:
    discovery:
      register-enabled: true
      # nancos地址
      server-addr: localhost:8848
      # app-enabled: false
      metadata:
        dubbo:
          metadata:
            revision: 0
    config:
      enabled: true
      server-addr: localhost:8848
      # app-enabled: false
dubbo:
  provider:
    timeout: 10000
  scan:
    base-packages: com.o2o.mix.app.push.service
  application:
    name: ${spring.application.name}_dubbo_service
    qosEnable: false
    qosAcceptForeignIp: false
    qosPort: 1234
    #status-enabled: true
  registry:
    dynamic: true
    # address: nacos2://${nacos.addr}?appListenerEnable=true
    address: nacos://localhost:8848
    parameters:
      registry-type: service
  protocol:
    name: dubbo
    host: ${local-ip}
    port: -1
  configCenter:
    address: nacos://localhost:8848
  metadataReport:
    address: nacos://localhost:8848
server:
  port: 8016
