server:
  port: 9015
  servlet:
    context-path:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatisplus-md?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          &allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    password: dadada
    username: root

